name: CodeMender Testing

on:
  workflow_dispatch: 

jobs:
  CodeMender-Scan:
    uses: Codemender-Demo/cm-github-actions/.github/workflows/codemender.yml@main
    secrets:
      workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
      service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

